TOKEN = "YOUR_BOT_TOKEN"
PAYMENTS_TOKEN = "YOUR_PAYMENTS_TOKEN"

host = 'YOUR_DB_HOST'
port = 'YOUR_DB_PORT'
db_name = 'YOUR_DB_NAME'
user = 'YOUR_USERNAME'
password = 'YOUR_DB_PASSWORD'

channel_name = "YOUR_TELEGRAM_CHANNEL_NAME"
